/** Hand-written Listen mode scripts for Path A phases — coach voice for Web Speech API. */

export const phaseListenScripts: Record<string, string[]> = {
  'phase-0': [
    'Cold open. Before you call any Identity Security Cloud A P I, you need the nouns. If you confuse identity with account, or access request with lifecycle, you will design the wrong integration — and sound junior in a design review.',
    'By the end of this phase you should explain what I S C is for in one sentence, name the core objects and how they relate, and know when the U I is enough versus when you reach for an A P I or software development kit.',
    'I S C is the governance brain. It correlates people to accounts across connected systems, and it drives joiner, mover, and leaver decisions plus governed access.',
    'An identity is the person or machine I S C governs. An account is that identity’s record on a specific source — Active Directory, Salesforce, a SaaS app. One person usually has many accounts.',
    'A source is the connected system. Entitlements are permissions or groups on that source. Access profiles bundle entitlements. Roles sit higher — business-shaped access that often groups profiles.',
    'Lifecycle states like Active or Terminated live on the identity profile. They drive provisioning downstream. Aggregation pulls accounts and entitlements in. Provisioning pushes create, update, disable, or delete out.',
    'Picture the chain: identity profile and lifecycle sit above the identity; the identity connects to accounts on sources; entitlements hang off those; profiles and roles compose the access story. Certifications are periodic review campaigns. Access requests are governed asks with approvals.',
    'Say this in a design review: emergency disable sets a Terminated lifecycle — resolved by name, never by a hardcoded I D — so I S C cascades disables. Peer clone submits access requests; it does not bypass approvals.',
    'When do you reach for code? When an external system must trigger something — I T D R, S I E M, automation — or when the U I cannot express the workflow. Otherwise configure in product first.',
    'Watch out for these traps. Treating identity and account as synonyms. Hardcoding tenant-specific object I Ds. Waiting for the next H R file when security needs someone disabled now. Aggregation is batch and slow; compromised accounts need immediate A P I-driven action.',
    'When you’re back at the screen, take the vocab micro-check: one person with an A D login and a Salesforce login is one identity and two accounts. Then answer the drills out loud — entitlement versus profile versus role, why H R sync is not enough for I T D R, and when U I loses to A P I.',
  ],

  'phase-1': [
    'Cold open. This phase is about explaining a failing call without guessing. Auth and H T T P craft separate people who debug in minutes from people who rotate secrets at random.',
    'You should be able to walk a Personal Access Token through client-credentials end to end, separate user level from scopes, diagnose four oh one, four oh three, and four twenty-nine correctly, and store secrets with keyring discipline — never in source or chat.',
    'Scripts authenticate with a Personal Access Token — P A T — via OAuth client credentials. You post to the token endpoint, get a bearer token that lasts about twelve minutes, and send Authorization Bearer on A P I calls.',
    'Reuse one token for the run. The software development kit — S D K — refreshes tokens for you. Raw REST must not mint a new token on every call — that burns rate limits. Think on the order of about one hundred requests per access token per ten seconds.',
    'Modern P A T client I Ds are UUIDs with dashes. Legacy undashed I Ds fail. Authentication is not authorization. The token proves who you are; scopes and user level decide what you may do.',
    'Four oh one means the token is missing, expired, or invalid. Four oh three means the token worked, but you’re not allowed — missing scope, wrong user level on the P A T owner, or an endpoint that needs user context client credentials cannot provide. Four twenty-nine means back off and retry with respect.',
    'Say this when someone reports a four oh three with a valid token: don’t rotate the secret first. Check scopes, the owner’s user level, and whether the endpoint needs a user context that client credentials cannot supply.',
    'For a read-only reporting job, ask for specific read scopes — not scopes all — and pair that with a user level that can read but not mutate. Name P A Ts per integration so audit trails make sense.',
    'Secrets: this workshop uses python-keyring into the OS keychain. Never paste a client secret into chat. Never commit a dot env file. In production, use a vault. Revoke on offboarding.',
    'Watch-outs. Minting a token per request. Confusing four oh one with four oh three. Assuming a valid bearer token means every endpoint will accept it. Quoting rate limits as gospel without checking current docs when S L As matter.',
    'When you’re back at the screen, take the micro-check on create access request returning four oh three — the answer is missing scope or insufficient user level, not a bad secret. Then drill aloud: walk the bearer token flow, explain that four oh three, and state least-privilege scoping for a read-only job.',
  ],

  'phase-2': [
    'Cold open. This is the most important fluency upgrade in July two thousand twenty-six. You must be bilingual about A P I versioning — or every design conversation will age poorly.',
    'Outcomes: contrast yearly versus per-service models accurately, map a legacy path to a new path, recommend greenfield to per-service v N and brownfield migrate before Q one twenty twenty-nine, and explain public versus experimental with the experimental header.',
    'Legacy yearly collections still work — slash v two zero two six slash accounts, slash v three, beta, and even slash latest. But greenfield work targets per-service paths like slash identities slash v one, slash accounts slash v one, slash access-requests slash v one.',
    'Why did SailPoint move? Yearly bumps forced churn even when a service had no breaking change. Per-service semantic versioning only bumps majors when the contract actually breaks. Docs flatten to current service docs first; legacy specs stay for maintenance.',
    'Slash latest was introduced early twenty twenty-six as a yearly-alias shortcut. Under the July twenty twenty-six strategy, treat it as unsafe for production. It auto-routes and can break silently when routing flips. Prefer explicit slash service slash v N pins.',
    'Legacy yearly, v three, and beta still have support tickets through Q two twenty twenty-eight, and hard end of life in Q one twenty twenty-nine. Migration is urgent strategically but not overnight — the deadline is Q one twenty twenty-nine. Brownfield inventories and migrates; greenfield does not start on yearly paths.',
    'In the TypeScript software development kit two point x, you import resource A P Is without year namespaces, and method names carry the version suffix — list accounts v one, and so on. Old S D Ks used year namespaces on the class. Use the official migration scripts; don’t hand-rewrite everything. Review v two outliers by hand — some access-request-config and entitlements cases already map to v two.',
    'Experimental endpoints still need the header X hyphen SailPoint hyphen Experimental set to true. They may break with little notice. Public A P Is avoid breaking changes within a major version.',
    'Say this to leadership: we pin per-service versions for new work. We inventory scripts and workflow H T T P actions for yearly and slash latest debt. We migrate with official scripts and the path table before end of life — support ends Q two twenty twenty-eight; endpoints stop Q one twenty twenty-nine.',
    'Watch-outs. Shipping slash latest because it always follows current. Treating Q one twenty twenty-nine as someone else’s problem with no inventory. Assuming every migrated path is v one. Using this workshop’s yearly samples as the greenfield default — great for patterns, wrong as the target for new code.',
    'When you’re back at the screen, take the path-shape micro-check: greenfield emergency disable picks slash identities slash v one, not yearly or slash latest. Then drill: why yearly was abandoned, is slash latest O K in production mid twenty twenty-six — no — and whether sailpoint dot v two zero two five is broken yet — not yet, but plan the migration.',
  ],

  'phase-3': [
    'Cold open. Domain fluency means you can design an integration verbally — joiner, mover, leaver, emergency disable, access request, peer clone, and search — before you open an editor.',
    'The outcome is simple to say and hard to fake: pick the right objects and the right call sequence without guessing. Resolve by name. Verify after mutate. Preserve governance.',
    'Module three A — identities, accounts, lifecycle. Find the identity with a filter on alias or name. Never hardcode lifecycle state GUIDs — they are tenant-specific. List lifecycle states on the identity profile, find Terminated by name, set the lifecycle state, then G E T to confirm before and after.',
    'Say this for emergency disable: I set lifecycle to Terminated, resolved by name, so Identity Security Cloud provisions disables downstream. I don’t invent per-app disable loops unless the source is unmanaged.',
    'Module three B — access requests and approvals. You can request roles, access profiles, or entitlements. Approvals still apply. Cancel, close, and status A P Is exist. Some config paths may be on v two after migration — check the table.',
    'Say this for peer clone: peer clone should submit access requests, not bypass governance. Dry-run first, then submit.',
    'Module three C — sources and entitlements. Accounts live on sources. Entitlements hang off accounts. Aggregation has latency; real-time A P I action is a different clock. Don’t design as if the last aggregate is always fresh.',
    'Module three D — Search. Search is index queries, not the same as list filters. Limit can go up to ten thousand, then page with search after. Prefer collection filters for straightforward real-time I T D R lookups; use Search for richer analytics where index lag is acceptable.',
    'Module three E — collection parameters, filters, and P A T C H. Memorize operators: equals, not equals, contains, starts with, greater and less than family, present, in, and, or. P A T C H uses JSON Patch with the json-patch content type — not a casual partial JSON body.',
    'Worked sequence for a leaver: resolve identity by alias, resolve lifecycle I D by name, set state, verify with G E T. That pattern is the spine of scenario one in this repo — rewrite it mentally onto slash identities slash v one paths for current work.',
    'Watch-outs. Hardcoding Leave of Absence or Terminated I Ds. Disabling accounts in a for-loop while ignoring lifecycle. Using Search when a simple list filter would do — or the reverse for huge reporting. Skipping dry-run on peer clone. Forgetting verify G E T after mutation.',
    'When you’re back at the screen, take the micro-check on disabling Jennifer Thomas — first step is G E T identities with an alias filter, then resolve lifecycle by name. Drill aloud: find identity without a GUID, what’s wrong with hardcoding a lifecycle I D, and when Search beats list filters.',
  ],

  'phase-4': [
    'Cold open. TypeScript is first-class for Identity Security Cloud — but it appears in three surfaces. Conflating them in conversation is a senior tell in the wrong direction.',
    'Outcomes: scaffold a TypeScript A P I project with the SailPoint C L I, call a v one method with filters, and explain when you’d write a connector instead of an external script.',
    'Surface one: the I S C A P I software development kit — sailpoint-api-client on npm. You use it to call I S C REST from Node or TypeScript apps. Nightly compliance jobs live here.',
    'Surface two: SaaS Connectivity — the connector S D K plus the local spcx debugger. That is for custom cloud connectors and loopbacks — aggregate and provision semantics for a Source.',
    'Surface three: connector customizers — TypeScript hooks that mutate before or after out-of-the-box connector operations. Different problem than calling the platform A P I from a cron job.',
    'In sailpoint-api-client two point x, method versioning is in the name. Import resource A P Is without year namespaces. Call list accounts v one, list transforms v one, and so on. Legacy one point x used year namespaces on the class — Accounts V two zero two five A P I — and plain method names.',
    'Scaffold with the C L I: sail sdk init typescript for a project, sail sdk init config for credentials shape. Migration from one point x to two point oh uses the official migration script — then review outliers.',
    'Say this in review: for a nightly compliance report in Node, I use the A P I S D K. For a new SaaS H R app with no out-of-the-box connector, I reach for the connector S D K. Same language, different job.',
    'Offline practice shape: load base URL, client I D, and client secret from environment — with the same keyring discipline as this workshop’s Python path — and sketch disable identity by alias with clear steps and a to-do for live calls. Compare that design to scenario one’s REST style — same integration, different caller language.',
    'Watch-outs. Importing the connector S D K for a reporting job. Hand-rolling yearly paths in a new TypeScript service. Skipping the migration script and renaming classes by guesswork. Treating workshop yearly samples as the greenfield TypeScript default.',
    'When you’re back at the screen, take the surface micro-check — nightly Node compliance is the A P I client, not SaaS Connectivity. Then drill: how method versioning works in the TypeScript S D K two point x, and A P I S D K versus connector S D K for compliance versus a net-new SaaS H R app.',
  ],

  'phase-5': [
    'Cold open. Picking the wrong runtime is how good designs become unmaintainable handoffs. This phase is the decision tree: TypeScript, Python, Go, PowerShell, raw REST, and the SailPoint C L I.',
    'The outcome: choose among those tools for a real scenario, and know when the C L I scaffolds versus when you ship an integration spec.',
    'Decision rule from this workshop: if the code runs on its own as a script or service you own — use a software development kit. If another system is calling Identity Security Cloud — ITDR, SIEM, ServiceNow, webhooks — give them direct REST, not an S D K import.',
    'TypeScript S D K: Node services, SaaS connectors, modern web tooling. Python S D K: automation scripts, data and ops — this workshop’s home turf. Prefer Python two point x for new work; this repo pins one point four for workshop compatibility with yearly namespaces.',
    'Go and PowerShell: platform preference, Windows ops, compiled services — same per-service mental model and migration story. SailPoint C L I: project init, config, connector workflows — not a substitute for production auth design.',
    'Direct REST means a language-agnostic call sheet: method, path, headers, body, required scopes, Personal Access Token guidance. Paths should be per-service — slash service slash v N — not yearly and not slash latest.',
    'Migration story for each S D K: official scripts rewrite year or beta namespaces to resource A P Is and add version suffixes on methods. Review v two outliers manually. Align clients with per-service paths before Q one twenty twenty-nine.',
    'Say this when ServiceNow asks for the Python package: usually no. Give them a REST call sheet, P A T scopes, and pinned per-service paths. The S D K belongs in a process you own and run.',
    'Worked example: refactor one scenario’s shape into an OpenAPI-oriented call sheet for another platform — method, path spoken as slash identities slash v one style, headers including bearer token, body, and verify G E T. That is an integration spec, not a long-running S D K app.',
    'Watch-outs. Asking another team to npm install or pip install your favorite S D K. Putting slash latest in a handoff doc so they never migrate. Treating workshop one point four Python imports as the forever standard. Forgetting the C L I exists for scaffold and then reinventing project layout.',
    'When you’re back at the screen, take the ServiceNow micro-check — best artifact is REST call sheet plus P A T scopes plus per-service paths. Then drill: should ServiceNow import Python — usually no — and what’s the migration story across S D Ks.',
  ],

  'phase-6': [
    'Cold open. Not every problem is write a script against the A P I. Conversational developers know the extension-point menu and pick the lightest tool that fits.',
    'Outcome: name transforms, rules, workflows, SaaS Connectivity, customizers, and external integrations — and choose correctly for a use case.',
    'Transforms are JSON config for attribute calculate and map on aggregate or provision. Prefer them over rules when possible. Deterministic string normalize — lowercase an H R email into an identity attribute — is transform vocabulary.',
    'Rules are BeanShell for logic transforms cannot express. Expect SailPoint review and install constraints. Don’t reach for a rule because it feels more powerful — reach for it when transforms truly cannot express the logic.',
    'Workflows are low-code plus H T T P actions for event-driven process automation. Scan those H T T P actions for legacy yearly paths and slash latest. Use Workflow Analyzer mindset: find them, rewrite to per-service paths, verify before Q one twenty twenty-nine.',
    'SaaS Connectivity is TypeScript custom connectors in SailPoint cloud — target reachable from cloud, spcx for local debug. Connector customizers are TypeScript hooks to tweak out-of-the-box connector input and output — more flexible than classic rules for many SaaS sources.',
    'External integrations remain this curriculum’s core: any language via A P I for ITDR, H R, SIEM, ticketing — Personal Access Token plus per-service call sheet.',
    'Decision tree in words: attribute mapping only — transform. Event side effects over H T T P — workflow. Need a new Source to aggregate and provision — SaaS Connectivity. Tweak an out-of-the-box connector’s I O — customizer. Complex BeanShell only — rule. Otherwise external A P I script.',
    'Say this: prefer transforms before rules. Prefer workflows for event side effects. Prefer connectors when you need a Source. Prefer external A P I when another system owns the trigger. A loopback connector is appropriate when you want I S C to manage I S C objects as if they were a target system — SaaS Connectivity plus the A P I S D K inside the connector.',
    'Watch-outs. Cloud rule for a lowercase. Workflow H T T P still on slash v two zero two five with no migration plan. Building a nightly invent-accounts script instead of a connector for a net-new SaaS app. Skipping Workflow Analyzer while declaring migration done.',
    'When you’re back at the screen, take the micro-check — lowercase H R email on aggregation is a transform. Then drill: transform or rule, risk of workflow H T T P on yearly paths, and when a loopback connector is appropriate.',
  ],

  'phase-7': [
    'Cold open. Production craft is how you sound like someone who has shipped Identity Security Cloud integrations — not someone who only completed a tutorial.',
    'Outcome: talk secrets, verify-after-mutate, pagination, object I D discipline, version pins, observability, and agentic development as standards — then capture them in a one-page A D R.',
    'Secrets: one Personal Access Token per integration. Track expiration. Revoke on offboarding. Keyring locally; vault in production. Never paste secrets into A I tools or commit them. Name P A Ts for audit.',
    'Idempotency and verify: after any mutation — lifecycle change, account disable, access request submit — follow with a G E T. Show before and after. That evidence is required for ITDR and audits. Assuming success is not a strategy.',
    'Pagination and bulk: limit, offset, and count on collections. Search uses search after past large result sets. Batch thoughtfully. Respect four twenty-nine with backoff. Don’t melt the tenant with eager parallelism.',
    'Object I D discipline: resolve by name every time. Tenant GUIDs are not portable across sandbox and prod. Lifecycle states, roles, access profiles, sources — none of them travel as hardcoded I Ds.',
    'Change management: prefer slash service slash v one pins. Treat experimental as non-prod. Watch the deprecated response header. Slash latest is not a production versioning strategy under the July twenty twenty-six model.',
    'Observability: log request I Ds and correlation. Monitor deprecation headers. Name integrations so operators can find the owner. Agentic development: local OpenAPI plus project rules beat model memory — especially during the twenty twenty-six versioning transition.',
    'Say this in your A D R title line: greenfield I S C integration standards for our team, July twenty twenty-six. Include auth with P A T and least privilege, S D K versus REST decision rule, per-service version pins, secret storage, dry-run flags, verify G E T, and the migration deadline — support through Q two twenty twenty-eight, hard end of life Q one twenty twenty-nine.',
    'Watch-outs. Secrets in chat. Skipping verify after mutate. Hardcoded GUIDs. Shipping slash latest. Ignoring four twenty-nine. Declaring migration done because the S D K upgraded while a cron still hits yearly paths.',
    'When you’re back at the screen, take the micro-check — after set lifecycle state, G E T and compare before and after. Then drill three production must-haves aloud, and draft or refine that one-page A D R before you leave the phase.',
  ],

  'phase-8': [
    'Cold open. Capstones and drills turn fluency into habit. Design deliverables plus a weekly fifteen-minute conversation practice — that is how you sound senior when it counts.',
    'Outcome: complete capstones A through D, keep a weak-topic queue honest, and run the weekly drill without notes on the Snapshot facts.',
    'Capstone A — emergency disable as an integration spec. Deliver a language-agnostic REST call sheet plus a TypeScript sketch using current slash service slash v one paths. Compare to scenario one. Name-resolve identity and lifecycle. Verify with G E T.',
    'Capstone B — compliance bridge. Design nightly automation: external C S V to rules to lifecycle or access request. Python or TypeScript. Dry-run mode required. No silent mutate in production without a switch.',
    'Capstone C — peer access provisioner. Port scenario three’s design to software development kit two point x method names even if you cannot execute live. Include the approval-preserving narrative — submit requests, don’t bypass governance.',
    'Capstone D — migration advisory. Given a fictional inventory — v two zero two four scripts, v two zero two five workflows, one slash latest job — produce a plan. Inventory, map via the official table, run S D K migration scripts, scan workflow H T T P with Analyzer mindset, replace slash latest with pinned per-service paths, test, and track to Q two twenty twenty-eight support end and Q one twenty twenty-nine hard end of life.',
    'Weekly fluency drill — fifteen minutes. Pick three. Explain yearly versus per-service to a manager. Debug a fictional four oh three. Name five filter operators with examples. Sketch a TypeScript list X v one call from memory. Argue transform versus rule versus workflow. Map one legacy path to a new path.',
    'Say this to a manager in two sentences: we used to bump every A P I every year even when nothing changed. Now each service stays on slash service slash v one until that service actually breaks its contract — and we migrate legacy before Q one twenty twenty-nine.',
    'Keep the Snapshot table memorized: per-service versioning is current, slash latest is unsafe for production, support tickets through Q two twenty twenty-eight, endpoints stop Q one twenty twenty-nine, P A T tokens about twelve minutes, diagnose four oh one versus four oh three versus four twenty-nine without guessing.',
    'Watch-outs. Capstones that still ship yearly paths as greenfield. Dry-run missing on compliance and peer clone designs. Declaring fluency without saying Q two twenty twenty-eight and Q one twenty twenty-nine aloud. Skipping the weak queue because the happy path feels fine.',
    'When you’re back at the screen, open the capstone labs and the weekly drill list. Take the manager-explanation checkpoint. Run one fifteen-minute drill today — three prompts, out loud, no notes — then mark weak topics for next week.',
  ],
}
