/** Track 1 (API craft) Listen scripts — coach voice, TTS-friendly. */

export const moduleListenScriptsTrack1: Record<string, string[]> = {
  m4: [
    'Cold open. Module four is REST in any language — the integration-spec skill. The wrong deliverable wastes weeks. Handing ServiceNow the Python S D K forces their team to host a runtime they do not own. Giving yourself only a Postman collection skips retries, pagination, and typed clients you will need when the one-shot becomes a product.',
    'Outcomes for this module. You can write method, U R L, headers, body, expected status, and a verify GET for a multi-step flow. You can choose a REST integration-spec when the caller is I T D R, SIEM, ServiceNow, or a webhook — not a long-running S D K app you own. And you can handle token reuse, pagination, and four twenty-nine in language-agnostic terms.',
    'Teach — the decision rule. If the script runs on its own in a runtime you own, prefer the official S D K two point x — it handles auth refresh, retries, pagination helpers, and experimental headers. If another system must call Identity Security Cloud — I S C — give a REST call sheet plus Personal Access Token — P A T — guidance. One-shot Postman is fine to explore; graduate to S D K when it becomes yours to operate.',
    'Teach — what a call sheet must contain. Base U R L, auth steps, and scope list. Every step: H T T P method, path pinned as slash service slash v N, headers, sample body, expected success status codes. Explicit name-to-I D resolution steps. An error matrix covering four oh one, four oh three, four oh four, four twenty-nine, and business four hundreds. Owner team and P A T naming convention.',
    'Teach — emergency disable skeleton in words. Post to the OAuth token endpoint with client credentials. Get identities with a filter alias equals the target, using slash identities slash v one. List lifecycle states on the identity profile and pick the name Terminated. Post set-lifecycle-state on that identity with the resolved lifecycle state I D. Get the identity again to verify after state. Document that provisioning may still be asynchronous after I S C accepts the call.',
    'Teach — production craft on the wire. Reuse one bearer token per run. Paginate with documented limit and offset or search-after patterns. On four twenty-nine, back off with jitter. Pin slash identities slash v one style paths — never hand off slash v two zero two six or slash latest as “current.” State idempotency expectations: what happens if the same disable is posted twice.',
    'Example — say this to a ServiceNow team. You should not import the Python sailpoint package. Here is a REST call sheet: method, path, headers, body, status, name resolution, and verify GET. Here are the scopes on a dedicated P A T. Success means verified lifecycle state, not merely a two oh two accepted.',
    'Example — say this in architecture review. Script-on-its-own goes S D K. Other-system-calls-I S C goes REST integration-spec. If security asks for a contract-first review, the call sheet is the artifact — not a private repo of S D K samples they cannot run inside their platform.',
    'Failure modes. Giving ServiceNow the Python S D K as the integration contract. Omitting the verify GET and assuming mutation is done. Hardcoding a lifecycle state UUID in the call sheet. Using yearly or slash latest paths in a handoff labeled current. Skipping the error matrix so on-call cannot distinguish auth failure from authorization failure.',
    'Failure modes, continued. No owner or rotation date on the P A T. Call sheets that list happy path only. Treating async provisioning as synchronous completion. Shipping a Postman collection with sandbox I Ds still embedded.',
    'Screen close. Module four: choose the deliverable by who runs the code. REST call sheets for external platforms; S D K for automations you operate. Pin per-service paths, resolve names, verify with GET. Next is filters, Search, PATCH, and bulk — how you query and update at scale.',
  ],

  m5: [
    'Cold open. Module five is filters, Search, PATCH, and bulk patterns. Picking Search for an I T D R disable can hit index lag and miss the identity you must act on now. Picking list plus deep offset for a million-row analytics dump burns rate budget and time. Choose the tool by workload.',
    'Outcomes for this module. You can write standard collection filters with equals, starts with, contains, in, and, and correct quoting. You can choose list filters versus Search with search-after for the right workload. And you can apply JSON Patch with the correct content type and respectful bulk and pagination.',
    'Teach — list filters. Collection list A P Is take a filters query for simpler predicates. Examples you should be able to say: alias eq, then the quoted value. Name starts with a quoted prefix. First name starts with and status equals ACTIVE. Created greater than an I S O timestamp. Name in a quoted list. Identity I D equals a quoted GUID. Unquoted strings are a classic four hundred.',
    'Teach — Search versus list. List plus filters gives near real-time resource collections with limit and offset pagination — prefer this for I T D R and simple alias lookups when the collection A P I supports them. Search uses an index query language; page with search-after after large limits — great for wide reporting and reconciliation, but accept possible index lag. Search is not a substitute for an authoritative identity GET when you already have the I D.',
    'Teach — PATCH versus PUT. Partial updates use JSON Patch operations — add, replace, remove — with content type application slash json-patch plus json. PUT of an entire object from a stale GET loses concurrent updates. Prefer PATCH when you mean to change specific fields only.',
    'Teach — bulk and rate respect. Batch within rate limits; prefer documented server bulk endpoints when they exist. Verify a sample of results after bulk jobs. Reuse one token; retry four twenty-nine with jitter. Deep offset pagination on huge sets has a cost — measure it or switch to search-after for analytics-scale reads.',
    'Example — say this for an identity lookup. For alias Jennifer dot Thomas, use list identities with filters alias eq, quote Jennifer dot Thomas, against slash identities slash v one. Do not open Search first for a single known alias when the list filter works.',
    'Example — say this for a reporting job. Broad, index-oriented queries and large result sets use Search and search-after. Document that results may lag the live identity store. For real-time disable when you already have the identity I D, skip search theater — get and mutate directly.',
    'Failure modes. Unquoted strings in filters producing four hundreds. Using Search on the I T D R path that needs an authoritative identity. PUT entire objects from stale GETs. Offset walking millions of rows without measuring cost. Wrong PATCH content type so the server rejects or misreads the body.',
    'Failure modes, continued. Replacing governed access changes with blind PATCH of assignments. Bulk jobs with no dry-run or progress metrics. Ignoring four twenty-nine and hammering the tenant. Treating Search hit counts as proof the identity does not exist.',
    'Screen close. Module five: filters for precise near-real-time lists, Search for wide analytics with lag awareness, JSON Patch for partial updates, bulk with verification. Next module applies this craft to identities, lifecycle, and emergency disable sequences.',
  ],

  m6: [
    'Cold open. Module six is identities, accounts, lifecycle, and sources — joiner, mover, leaver, and emergency disable. Hardcoding a Terminated GUID works once in sandbox and fails silently in prod. Skipping the verify GET closes the ticket while provisioning may still be in flight.',
    'Outcomes for this module. You can resolve an identity by alias and resolve a lifecycle state by name on the identity profile. You can explain account versus identity disable and when each is appropriate. And you can account for aggregation latency versus A P I-driven action when security needs seconds, not the next H R file.',
    'Teach — identity versus account. Identity Security Cloud — I S C — governs the identity. Accounts live on sources. Filter accounts by identity I D or by native identity plus source. Disabling one Active Directory account is not the same as offboarding the identity. Lifecycle on the identity profile drives provisioning to managed sources.',
    'Teach — aggregation versus A P I action. Aggregation pulls truth from authoritative sources on a schedule. Do not wait for the next H R file when a compromised account must be stopped now. Prefer A P I-driven lifecycle change for emergency disable. Unmanaged or break-glass sources may need direct account disable in addition to lifecycle.',
    'Teach — the emergency disable sequence. Get identities with filters alias eq the target on slash identities slash v one — capture before state. List lifecycle states for that identity’s profile; pick the state whose name is Terminated — never a hardcoded GUID. Post set-lifecycle-state with the resolved lifecycle state I D. Get the identity again and record after state in the run log.',
    'Teach — path pins for new work. Prefer slash identities slash v one, slash accounts slash v one, and slash sources slash v one. Resolve source names when you must target a specific account. Document correlation attributes so operators know how alias, email, or employee number map to the identity you intend to change.',
    'Example — say this to I T D R. We will not wait for H R aggregation. We resolve the identity by alias, resolve Terminated by name on the profile, set lifecycle, then verify with GET. Managed sources should receive disable provisioning from that lifecycle change. Call out any unmanaged source that still needs a direct account disable.',
    'Example — say this about hardcoding Leave of Absence. I Ds are tenant-specific and differ by environment. Resolve by name from the identity profile’s lifecycle states each run. Sandbox GUIDs in a production job are a silent no-op or a wrong-state mutation waiting to happen.',
    'Failure modes. Hardcoding Leave of Absence or Terminated GUIDs. Disabling one account and declaring the identity offboarded. No verify GET — ticket closed on H T T P accepted alone. Racing with aggregation that overwrites an attribute you patched on the account. Using access request to remove access for a compromised leaver.',
    'Failure modes, continued. Bulk J M L jobs without dry-run. Missing before and after evidence in logs. Assuming every source is lifecycle-managed. Confusing Search lag with “identity not found” during an incident.',
    'Screen close. Module six sequence to memorize: resolve identity, resolve lifecycle state by name, set state, verify with GET. Lifecycle for emergency offboard; account disable for unmanaged edges; never wait on the H R file when security needs now. Next is access requests, peer clone, and certifications — automate access without bypassing governance.',
  ],

  m7: [
    'Cold open. Module seven is access requests, roles, and certifications. Automation is a requester, not a backdoor. Prefer slash access-requests slash v one for create and status patterns. Approvals, segregation of duties, and audit still apply — peer clone that assigns entitlements directly is a governance failure dressed as productivity.',
    'Outcomes for this module. You can submit access requests for roles, access profiles, or entitlements with approvals intact. You can design peer clone as dry-run then request, not direct grant. And you know where certification and request-config A P Is sit — including v two outliers on the migration table.',
    'Teach — access request posture. Joiner role packages, peer clone, and training enrollment should create access requests, then poll or webhook for status. Cancel and close paths need error handling. Do not treat “request submitted” as “access granted” in success metrics — pending approval S L As still matter.',
    'Teach — peer clone pattern. Collect the peer’s roles and entitlements. Produce a dry-run artifact for manager or audit review. Submit access requests for the approved set. Never copy access by raw entitlement assignment A P Is unless written policy explicitly allows it. Resolve role and access profile I Ds by name at runtime — sandbox GUIDs fail in prod.',
    'Teach — certifications literacy. Certification campaigns review and revoke access on a schedule. Integrations usually report, kick off, or sync decisions — they do not replace I T D R emergency disable. Do not confuse a campaign revoke with setting Terminated lifecycle. Read scopes carefully; campaign A P Is are easy to over-privilege.',
    'Teach — version foot-guns. Prefer slash access-requests slash v one for common create and status flows. Some access-request-config and entitlements paths map to v two, not v one — verify in the official migration table. Leaving request-config calls on legacy yearly paths is unfinished migration hiding in admin tooling.',
    'Example — say this when someone asks why peer clone cannot just grant. Because approvals, segregation of duties, and audit are the product. Direct grants bypass the business controls the access model exists to enforce. Dry-run then access request is the senior pattern.',
    'Example — say this when choosing revoke tools. Compromised user who must lose access now is module six — lifecycle or account disable. Scheduled business review of who still needs a role is certification. Day-two business access with a manager in the loop is access request. Pick the lane; do not mash them together.',
    'Failure modes. Direct entitlement assignment to skip approvals. Submitting requests with sandbox role GUIDs in production. Ignoring pending approval S L As in automation success dashboards. Leaving access-request-config on yearly paths. Using certification revoke language for an emergency disable runbook.',
    'Failure modes, continued. Over-scoped certification Personal Access Tokens. No cancel or close handling when requests stall. Peer clone without a dry-run artifact. Treating request accepted as provisioned complete without status follow-up.',
    'Screen close. Module seven: access requests preserve governance; peer clone is dry-run then request; certifications are review campaigns, not I T D R. Pin slash access-requests slash v one, check v two outliers, resolve access objects by name. That closes the A P I craft track’s governance lane — carry the same verify-after-mutate discipline into every later module.',
  ],
}
